### ISSUE TITLE
Missing 0/flexrules.short_XC and "Cannot open file training_data_V/t for writing" error

### ISSUE THREAD

**Issue by khoidt** [kuhumcst/affixtrain#1]
Dear @BartJongejan, thank you for your work on Affixtrain and for making it available on Github. I would like to try it with Sumerian, but I have stumbled upon the following issues. The Affixtrain I am using is a Windows executable I built yesterday with your code.

1. The program runs on the example data, but `flexrules.short_XC` is not being created in `/0/` (contains the files `flexrules.short_A_XC`, `flexrules.short_ADV_XC`, `flexrules.short_N_XC`,  `flexrules.short_NUM_XC`, and `flexrules.short_V_XC`) or elsewhere. 

2. When I am trying to test Affixtrain on Sumerian data (packed in a file with the same structure as `short` in the example folder), it first seemingly runs as expected, creating the numbered folders and a plenty of files. However, unlike when it runs with the example data, a lot of messages like
 `!f1 (output tmp\out--_XC-N:DN_affixsingleshotincSize_5_9856_1.txt) PRESS ENTER` 
appear. The program stops with the following message: 
`Open files: 1721`
`Single tag input file: Cannot open file training_data_V/t for writing (wb). Exiting.`
Just as in 1, The expected `flexrules.training_data_XC` is also nowhere to be found.

I'd be very grateful if you could tell me what might be the cause of those, what I could do wrong and how to fix it. Many thanks in advance!

**Comment by BartJongejan** [comment]
Dear @khoidt, thank you for your interest in affixtrain.

1) The problem is caused by new default behaviour when the -n option is missing. Affixtrain assumes you want flexrules for each tag if there are more than two columns in the training data. Just adding -n FL should fix the problem. I have edited example/readme.txt to reflect the change.

2) The file name training_data_V/t seems to indicate that names of tags in your training data can contain a solidus (/). That character is problematic as it is interpreted as a path component separator by affixtrain.
